/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TugasAkhir;

import java.awt.Frame;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author lordk
 */
public class FromLogin extends javax.swing.JFrame {

    /**
     * Creates new form FromLogin
     */
    private void login(){
          if (tfUserName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Username Belum Di Isi");
            tfUserName.requestFocus();
        }
        else if(tfPassword.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Password Belum Di Isi");
            tfPassword.requestFocus();
        }
        else if(tfUserName.getText().equals("Admin") && tfPassword.getText().equals("Admin")){
        JOptionPane.showMessageDialog(null,"Login berhasil","SUKSES",JOptionPane.INFORMATION_MESSAGE);
        // memanggill file program ps2.java
        ProgramPS ps = new ProgramPS();
        ps.setVisible(true);
        ps.pack(); /* agar ukuran semua sub komponennya (misalnya, tombol, label, panel, dll.)
                    akan mendapatkan ukuran dan tata letak yang sesuai dengan kebutuhan
                     */
        ps.setLocationRelativeTo(null);// Menampilkan frame di tengah layar
        ps.setDefaultCloseOperation(FromLogin.EXIT_ON_CLOSE); //agar aplikasi akan benar-benar berhenti ketika jendela tersebut ditutup.
        this.dispose();//menutup jframe file fromLogin
        }
        else 
            JOptionPane.showMessageDialog(null, "Username atau Password tidak sesuai");
      
    }
    public FromLogin() {
        initComponents();
    // akan memfokuskan label judul
        jLabel1.requestFocus();
        iconShowPass.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        iconHidePass = new javax.swing.JLabel();
        iconShowPass = new javax.swing.JLabel();
        L_Password = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        L_Username = new javax.swing.JLabel();
        tfUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setLocation(new java.awt.Point(700, 300));
        setMinimumSize(new java.awt.Dimension(580, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(490, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/gamepad.btn.png"))); // NOI18N
        jButton1.setText("LOGIN");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 110, 40));

        iconHidePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/hidepass.png"))); // NOI18N
        iconHidePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconHidePassMouseClicked(evt);
            }
        });
        jPanel2.add(iconHidePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 40, 40));

        iconShowPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Showpass.png"))); // NOI18N
        iconShowPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconShowPassMouseClicked(evt);
            }
        });
        jPanel2.add(iconShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 40, 40));

        L_Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        L_Password.setForeground(new java.awt.Color(200, 200, 200));
        L_Password.setText("Masukan Password");
        jPanel2.add(L_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, 40));

        tfPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPasswordFocusGained(evt);
            }
        });
        tfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPasswordKeyPressed(evt);
            }
        });
        jPanel2.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 230, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password :");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 330, 70));

        L_Username.setBackground(new java.awt.Color(230, 230, 230));
        L_Username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        L_Username.setForeground(new java.awt.Color(200, 200, 200));
        L_Username.setText("Masukan Username");
        jPanel2.add(L_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, 40));

        tfUserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUserNameFocusGained(evt);
            }
        });
        tfUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfUserNameMouseClicked(evt);
            }
        });
        tfUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserNameActionPerformed(evt);
            }
        });
        tfUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUserNameKeyPressed(evt);
            }
        });
        jPanel2.add(tfUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 230, 40));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username :");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 330, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/computer2.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 210, 230));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/geometric-hex-backgrounds.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 290));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 560, 290));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KEY PLAYSTATION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 210, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 557, 394));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         login();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserNameActionPerformed

    private void tfUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUserNameKeyPressed
        //ketika tf username di enter
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        // fokus ke tekfield password
        tfPassword.requestFocus();
    }//GEN-LAST:event_tfUserNameKeyPressed

    private void iconShowPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconShowPassMouseClicked
        // TODO add your handling code here:
        // akan menghilangkan icon show password 
        iconShowPass.setVisible(false);
        // dan akan menampilkan icon hide password
        iconHidePass.setVisible(true);
        // tf password berubah setiap karakter menjadi bintang
         tfPassword.setEchoChar('*');
    }//GEN-LAST:event_iconShowPassMouseClicked

    private void iconHidePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconHidePassMouseClicked
        // TODO add your handling code here:
        iconShowPass.setVisible(true);
        iconHidePass.setVisible(false);
       //password akan ditampilkan secara langsung dan tidak disembunyikan oleh karakter lain
        tfPassword.setEchoChar((char)0);
    }//GEN-LAST:event_iconHidePassMouseClicked

    private void tfUserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfUserNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserNameMouseClicked

    private void tfUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUserNameFocusGained
        // TODO add your handling code here:
         L_Username.setVisible(false);
    }//GEN-LAST:event_tfUserNameFocusGained

    private void tfPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusGained
        // TODO add your handling code here:
        L_Password.setVisible(false);
    }//GEN-LAST:event_tfPasswordFocusGained

    private void tfPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPasswordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        login();
    }//GEN-LAST:event_tfPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_Password;
    private javax.swing.JLabel L_Username;
    private javax.swing.JLabel iconHidePass;
    private javax.swing.JLabel iconShowPass;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUserName;
    // End of variables declaration//GEN-END:variables
}
